# Generated by Django 5.2.3 on 2025-06-20 12:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='state',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='taluka',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='village',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='village',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='village',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='villagedata',
            name='data_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='villagedata',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='villagedata',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
